version: "3"
services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: myadmin
      MONGO_INITDB_ROOT_PASSWORD: myadminpassword
      MONGO_INITDB_DATABASE: mydatabase

  compass:
    image: mongo/mongosh
    container_name: my-compass
    depends_on:
      - mongodb
    command: mongosh --host mongodb -u myadmin -p myadminpassword --authenticationDatabase admin
    links:
      - mongodb

volumes:
  mongodb-data:
    driver: local
