version: "3"
services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - MONGO
    volumes:
      - ./mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: myadmin
      MONGO_INITDB_ROOT_PASSWORD: myadminpassword
      MONGO_INITDB_DATABASE: mydatabase

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: myadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: myadminpassword
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - MONGO
    depends_on:
      - mongodb

networks:
  MONGO:
    name: MONGO
