version: "3"
services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: youradminusername
      MONGO_INITDB_ROOT_PASSWORD: youradminpassword
      MONGO_INITDB_DATABASE: yourdatabase

  mongosh:
    image: mongo
    container_name: my-mongosh
    depends_on:
      - mongodb
    entrypoint: mongosh
    command: --host mongodb -u youradminusername -p youradminpassword --authenticationDatabase admin

volumes:
  mongodb-data:
    driver: local
