version: "3.8"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  bullboard:
    container_name: bullboard
    image: addono/bull-board
    restart: always
    ports:
      - 3050:3000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USE_TLS: "false"
      BULL_PREFIX: bull
      USER_LOGIN: "username"
      USER_PASSWORD: "password"
    depends_on:
      - redis
volumes:
  redis:
    driver: local
